### ISSUE TITLE
codecov.io code coverage reports (now requires secret token)

### ISSUE THREAD

**Issue by duttonw** [ckan/ckanext-validation#104]
Seems this stopped working a long time ago, 

@wardi , @amercader , As I don't have 'setting/admin' access to this repo, can you add the following. So that ``secrets.CODECOV_TOKEN`` is available for cicd.

https://app.codecov.io/github/ckan/ckanext-validation/config/general
collect token
add to github
https://github.com/ckan/ckanext-validation/settings/secrets/actions
``CODECOV_TOKEN`` 

More info here: https://docs.codecov.com/docs/quick-start

**Comment by amercader** [comment]
Done @duttonw , let me know if that worked
