### ISSUE TITLE
Upgrade frictionless dependency

### ISSUE THREAD

**Issue by ChasNelson1990** [ckan/ckanext-validation#87]
Hi @amercader,

So currently we're using a pre-release version of frictionless (v5.0.0b9) in this repo. It probably makes a lot of sense both stability wise and feature wise to move to the latest full release (v5.13.1) - any objections to me making a PR with the dependency updated?

There may be a few small changes required as I note a few things have changed between b9 and now but hopefully not much.

**Comment by amercader** [comment]
That sounds great @ChasNelson1990 , thanks for the offer

**Comment by duttonw** [comment]
[2.2.0](https://github.com/ckan/ckanext-validation/releases/tag/2.2.0) is now on frictionless==5.18.0
