### ISSUE TITLE
is there any reason to use the 5.0.0b9 version of frictionless?

### ISSUE THREAD

**Issue by KatiRG** [ckan/ckanext-validation#93]
I am testing out using custom checks such as [this example](https://framework.frictionlessdata.io/docs/guides/validating-data.html#custom-checks), and got an error that `type` is required (`frictionless/schema/field.py`). This requirement was removed in frictionless on June 13 (https://github.com/frictionlessdata/frictionless-py/commit/fdcb91eebc39d7e6449d13ad57a9c7165deea45e) and I'm wondering why the ckanext-validations repo is not using this version or later?

The [requirements file](https://github.com/frictionlessdata/ckanext-validation/blob/master/requirements.txt#L2) has frictionless pinned to `5.0.0b9`.

**Comment by aimalkhan** [comment]
there is a PR https://github.com/frictionlessdata/ckanext-validation/pull/88/files to update the version to 5.13.1

**Comment by duttonw** [comment]
[2.2.0](https://github.com/ckan/ckanext-validation/releases/tag/2.2.0) is now on frictionless==5.18.0
